# Site settings
title: 'WJM-HOME'  # Your Title

tagline: '柔弱、无欲，顺乎自然，但却具有强大的生命力'  # A brief tagline for your site
sidebar_image: /images/cover.jpg

encoding: UTF-8
markdown: kramdown

paginate: 8
paginate_path: "page:num"

#pygments: true
baseurl: "/blog2016"


# Site settings
name:           wangjiangman
email:          fiona_914@163.com
uri:            wangjiangman.github.io
github:         wangjiangman2016
twitter:        wangjiangman2016
facebook:       wangjiangman2016
linkedin:       wangjiangman2016

